Karpenko Feature/ls cd
mkarpenkospb/ifmo-software-design pull request #2
Opened 2020-03-18 05:57 UTC by mkarpenkospb

2020-03-31 15:06 UTC, ottergottaott requested changes
Не работает ls с аргументами:
```
> ls shell
SHELL >> .git  .gitignore  .idea  shell 
```


Напоминаю, что требовалось 
> написать ревью на архитектуру оного одногруппника, указав, что оказалось удобным, а что неудобным при реализации, что можно было бы улучшить

2020-03-31 15:06 UTC, ottergottaott commented on shell/src/main/java/commands/Command.java
> +import java.io.IOException;
Это изменение лишнее, старайтесь делать чистые pr, пожалуйста

2020-03-31 15:06 UTC, ottergottaott commented on shell/src/main/java/commands/impl/CommandCd.java
> +public class CommandCd implements Command {
И тут тоже должны быть комментарии

2020-03-31 15:06 UTC, ottergottaott commented on shell/src/main/java/commands/impl/CommandCd.java
> +    public String name() {
Не нужно повторять ошибки за Вашим одногруппником, возвращайте здесь `name`.

`name` также должен быть private

2020-03-31 15:06 UTC, ottergottaott commented on shell/src/main/java/commands/impl/CommandCd.java
> +        File currDir = new File(currDirName);
Неиспользуемая переменная

2020-03-31 15:06 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandCd.java
> +        String currDirName = System.getProperty("user.dir");
Не стоит создавать переменные, если буквально парой строк ниже потенциально можете закончить работу функции.

2020-03-31 15:06 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandCd.java
> +        File targetDirFull = new File(targetName);
Попробуйте воспользоваться `Files.exists`, тогда не нужно будет создавать `File`.

Вместо платформозависимого
```java
currDirName + "/" + arguments.get(0)
```
можно воспользоваться `Paths.get`, он принимает произвольное количество аргументов (>1) и склеивает, если нужно.

2020-03-31 15:06 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandCd.java
> +        if (targetName.charAt(0) == '/' && targetDirFull.exists()) {
Я бы вынес условие
```
targetName.charAt(0) == '/'
```
в полноценный метод:
```
private boolean isPathAbsolute(String path) {
        return path.charAt(0) == '/';
    }
```
тогда чиатющему будет проще

2020-03-31 15:06 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandCd.java
> +        if (arguments.size() != 1)
> Обе команды могут принимать 0 или 1 аргумент

2020-03-31 15:10 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandCd.java
> +        } else {
А еще попробуйте как можно инвертировать условие и убрать какое-то ветвление, этот метод явно может быть лаконичнее

2020-06-08 22:19 UTC, mkarpenkospb commented on shell/src/main/java/commands/impl/CommandCd.java
> +        } else {
Сильно тут изменила.

2020-06-08 22:20 UTC, mkarpenkospb commented
Работает больше кейсов.

2020-06-09 13:22 UTC, ottergottaott requested changes
По функциональности все хорошо.

По коду замечания не очень значительные, поэтому засчитываю

2020-06-09 13:22 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandCd.java
> +            return "Wrong number of arguments!";
Скобочки

2020-06-09 13:22 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandLs.java
> +            return "Wrong number of arguments!";
Скобочки

2020-06-09 13:22 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandLs.java
> +        contents = dir.list();
Лучше пременные заводить ближе к месту использования и сразу инициализировать. + опять тернарный оператор кажется более читаемым:

```java
String pathName = arguments.size() == 0 ? System.getProperty("user.dir") :
        String.valueOf(CommandCd.getAbsolutePathToArgument(arguments.get(0)));
File dir = new File(pathName);

List<String> output = new ArrayList<>();
String[] contents = dir.list();
...
```

2020-06-09 13:22 UTC, aleksZubakov commented on shell/src/main/java/commands/impl/CommandLs.java
> +    String name;
`private`?

2020-06-09 14:04 UTC, mkarpenkospb commented
Комментарии к архиектуре Павла. Версия на момент форка его репозитория, то есть соответствует коду, в который я добавляла программы.

**Что понравилось**
Понятное разделение функциональности Shell на пакеты. 
Понравилось содержание класса `Environment` -- там есть все команды, основные пути, методы по обновлению окружения. 
Хорошо сделана промежуточная сборка компонентов программы через класс `CommandEntity`.  У меня было сделано иначе -- за промежуточный этап отвечает класс `Command`, затем набор команд превращается в набор уже иполняемых объектов класса `Program`, на которых непосредсвенно вызывается метод `run`. У Павла же выполнение происходит на объектах `Command` через `CommandExecutor`, который связывает команды с выполняемыми программами.  Оба варианта работают, мне сложно выбрать, какой лучше.

В архитектуте Павло было несложно понять, где и как имплементировать новые функции.
Познакомилась с билиотекой lombok, которая генерирует часть кода.

**Что можно было бы улучшить**
В одном методе `execute` класса `Executor` находится и парсинг пайпа, и его выполнение. Можно было бы выделить формирования набора исполняемых команд в отдельный метод. Там же осуществляется парсинг, подстановка переменных, частично что-то парсится в методе `execute`, что-то в методах предназначенных для этого классов `Parser` и `Substitutor`.  Хочется видеть процесс формирования команд как-то более линейно и последовательно. 

Как и я вначале, Павел реализовал пайп через передачу строк между командами. Нужно было использовать потоки. 

Пока для меня неясен смысл класса `CommandDefault`, возможно, это какой-то паттерн, полезный в некоторых случаях.

2020-09-12 17:40 UTC, merged